authorName: eoj-team
experimentName: eoj-next-problem
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 1000
trainingServicePlatform: local
searchSpacePath: search.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: maximize
trial:
  command: python train.py
  codeDir: ..
  gpuNum: 1
localConfig:
  useActiveGpu: true